#include "attribute/attribute.event.mligo"
#include "fight/fight.event.mligo"
#include "fighter/fighter.event.mligo"
#include "marketfighter/marketfighter.event.mligo"
#include "shop/shop.event.mligo"
#include "tournament/tournament.event.mligo"
