#include "fighter/fighter.schema.mligo"
#include "fight/fight.schema.mligo"
#include "tournament/tournament.schema.mligo"
#include "attribute/attribute.schema.mligo"
#include "ability/ability.schema.mligo"
#include "marketfighter/marketfighter.schema.mligo"
#include "shop/shop.schema.mligo"
